crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-1000
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-1200
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-1400
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-1600
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-1800
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-2000
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-2500
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-3000
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-3500
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-4000
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-4500
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-600
crab status -d crab_BulkGravToWWToWlepWhad_narrow_M-800
