crab submit -c crab3_analysisST_s-channel_4f_leptonDecays.py
crab submit -c crab3_analysisST_t-channel_antitop_4f_inclusiveDecays.py
crab submit -c crab3_analysisST_t-channel_top_4f_inclusiveDecays.py
crab submit -c crab3_analysisST_tW_antitop_5f_inclusiveDecays.py
crab submit -c crab3_analysisST_tW_top_5f_inclusiveDecays.py
crab submit -c crab3_analysisTT_TuneCUETP8M1.py
crab submit -c crab3_analysisWJetsToLNu_HT-100To200.py
crab submit -c crab3_analysisWJetsToLNu_HT-1200-2500.py
crab submit -c crab3_analysisWJetsToLNu_HT-200-400.py
crab submit -c crab3_analysisWJetsToLNu_HT-2500-Inf.py
crab submit -c crab3_analysisWJetsToLNu_HT-400-600.py
crab submit -c crab3_analysisWJetsToLNu_HT-600-800.py
crab submit -c crab3_analysisWJetsToLNu_HT-800-1200.py
crab submit -c crab3_analysisWZTo1L1Nu2Q.py
crab submit -c crab3_analysisZZTo2L2Q.py
